# name: Angular CI

# on:
#   push:
#     branches: [main]

#   pull_request:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Install Dependencies
#         run: npm install
    
#       - name: Run Tests
#         run: npm test -- --watch=false --browsers=ChromeHeadless

#       - name: Run Lint
#         run: npm run lint

#       - name: Build Angular App
#         run: npm run build


name: Angular Enterprise CI

on:
  push:
    branches: [main, develop]

  pull_request:
    branches: [main, develop]

jobs:

  lint:
    name: Lint Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run lint


  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm test -- --watch=false --browsers=ChromeHeadless


  build:
    name: Build Production App
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci
      - run: npm run build -- --configuration production